### ISSUE TITLE
Bad API request

### ISSUE THREAD

**Issue by waldyrious** [lattenwald/ElmReddit#2]
I tried running this locally, but when I click the "authorize" link in the index page, I get an error page from reddit titled "bad request" and saying:

> you sent an invalid request
> — invalid redirect_uri parameter.

The `redirect_uri` parameter in the url is `&redirect_uri=http://localhost:8000/index.html`. Is an actual domain needed for this to work?

**Comment by lattenwald** [comment]
In your API key settings at https://www.reddit.com/prefs/apps there's a "redirect url" parameter. It should be `http://localhost:8000/index.html` in your case.

Check it and respond back, please.

**Comment by lattenwald** [comment]
Ah yes, I got it. I used API key for my new domain, I'll fix that now…

**Comment by waldyrious** [comment]
Alright! It works now, thanks! (ps - sorry for the delayed response)
